name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Convco
        run: |
          curl -OL https://github.com/convco/convco/releases/latest/download/convco-deb.zip
          unzip convco-deb.zip
          sudo dpkg -i convco*.deb
        shell: bash
      - name: Generate Changelog
        run: convco changelog > CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          token: ${{ secrets.GH_TOKEN }}

  upload-assets:
    needs: create-release
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: vaultkeeper
          tar: unix
          zip: windows
          features: ${{ matrix.features || '' }}
          token: ${{ secrets.GH_TOKEN }}
